#!/usr/bin/env bash
set -euo pipefail

python -m defectfusion.cli evaluate-mvtec \
  --data-root /mnt/sda1/mvtec_anomaly \
  --model /mnt/sda1/DINOv3/dinov3-vitl16-pretrain-lvd1689m \
  --device cuda \
  --normal-shots 1 \
  --defect-shots 0 \
  --seed 42 \
  --image-size 672 \
  --pixel-image-size-override cable=896 \
  --pixel-image-size-override transistor=896 \
  --pixel-image-size-override pill=896 \
  --pixel-image-size-override screw=896 \
  --pixel-multiscale-size-override cable=672 \
  --pixel-multiscale-size-override transistor=672 \
  --pixel-multiscale-size-override pill=672 \
  --pixel-multiscale-size-override screw=672 \
  --pixel-multiscale-weight 0.25 \
  --resize-mode direct \
  --normal-augment-count 30 \
  --normal-augmentations rotate \
  --no-augment-categories transistor \
  --feature-layers=1,17,21,23 \
  --layer-aggregation mean \
  --layer-normalization none \
  --dual-branch \
  --anomaly-method pca_knn_anoco \
  --knn-weight 0.5 \
  --pixel-anoco-weight 0.10 \
  --anoco-neighbors 16 \
  --anoco-query-weight 2.0 \
  --anoco-temperature 0.07 \
  --anoco-affinity softmax \
  --anoco-anchor-ranking mean \
  --anoco-weight 0.25 \
  --anoco-layer-consensus \
  --fusion-mode fixed \
  --image-score mtop1p \
  --image-top-ratio 0.01 \
  --image-min-component-size 1 \
  --image-fusion-stage patch \
  --memory-max-patches 50000 \
  --knn-chunk-size 256 \
  --knn-backend torch \
  --knn-dtype float16 \
  --knn-spatial-radius 0.10 \
  --knn-spatial-categories cable transistor \
  --map-postprocess none \
  --type-matching bidirectional_patch \
  --top-k-ratio 0.05 \
  --output outputs/mvtec-pixel-anoco-multiscale-spatial
